### ISSUE TITLE
restore ?

### ISSUE THREAD

**Issue by yazgoo** [WATTx/gke-snapshooter#2]
Hi, Thanks for your tool which looks very nice.

could you give more information or pointers on how you restore a snapshot ?

Thanks

**Comment by eicca** [comment]
Oh, I'm sorry for a super-late response, I definitely missed the notification :)

Restoring is a bit manual job: https://cloud.google.com/compute/docs/disks/create-snapshots#restoresnapshotlargersize, but basically you can create a new disk based on some snapshot using `--source-snapshot` option.
